name: Build LaTeX Resume

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Setup LaTeX
      uses: xu-cheng/latex-action@v2
      with:
        root_file: resume.tex

    - name: Upload PDF
      uses: actions/upload-artifact@v3
      with:
        name: resume
        path: resume.pdf
